

#include <stdio.h>
#include <stdlib.h>
#include <time.h> 

char *getdatetime()
{
    char *array = (char*)malloc(sizeof(char)*25);
    time_t result;
    result = time(NULL);
    sprintf(array, "%s", asctime(localtime(&result)));
    array[25] = '\0';
    return array;
}

int main(int argc, char *argv[]) {

	if (argc > 1 && argv != NULL) {

		printf("Start\n");
		char *filename = argv[1];
		FILE *ptr = fopen(filename, "w");

		if (ptr) {
			char sDate[30];
			sprintf(sDate, "\t%s\n", getdatetime());

			char *ifdef  = "\n#ifndef __FILENAME__";
			char *define = "\n#define __FILENAME__";
			char *endif  = "\n#endif // __FILENAME__";

			fputs("\n/**\n\n", ptr);
			fputs("\tThis file has been generated by Pedro Ontiveros.\n", ptr);
			fputs("\tFilename: ", ptr);
			fputs(filename, ptr);
			fputs("\n\tAuthor: Pedro Ontiveros.\n", ptr);
			fputs("\temail: ontiveros.pedro@gmail.com\n", ptr);
			fputs("\ttwitter: pontiveros_ar\n", ptr);
			fputs(sDate, ptr);
			fputs("**/\n", ptr);

			fputs(ifdef, ptr);
			fputs(define, ptr);
			fputs(endif, ptr);
			
			fclose(ptr);
		}
		printf("End\n");	
	}
	exit(EXIT_SUCCESS);
}