

#include <stdio.h>
#include <stdlib.h>

int main(int argc, char *argv[]) {

	if (argc > 1 && argv != NULL) {

		printf("Start\n");

		FILE *ptr = fopen(argv[1], "w");

		if (ptr) {
			char *content = "\n/******************************************************/\n/** This file has been generated by Pedro Ontiveros. **/\n/******************************************************/\n\n\n#include <stdio.h>\n#include <stdlib.h>\n\nint main(int argc, char *argv[]) {\n\tprintf(\"Hello World!\\n\");\n\texit(EXIT_SUCCESS);\n}";
			fputs(content, ptr);
			fclose(ptr);
		}

		printf("End\n");	
	}
	exit(EXIT_SUCCESS);
}