/**

	This file has been generated by Pedro Ontiveros.
	Filename: ../../advanced/file_rw_sample.c
	Author: Pedro Ontiveros.
	email: ontiveros.pedro@gmail.com
	twitter: pontiveros_ar
	Sun Sep  4 19:33:42 EDT 2022

    clang: 
    $ clang -g source.c -o {binaryFile} ==> Result binary file + dsymb

    debug: 
    $ lldb {binary file} (object file)
    $ breakpoint set -file {source filename} --line {line}
    $ br s -f {source filename} -l {line}
    $ b {source filename} -l {line}
    $ next or n

**/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "tnode.h"

struct TNode *pList = NULL;

enum STORAGE_STATUS {
    FILE_WRITE_SUCCESS  = 1,
    FILE_WRITE_ERROR    = 2,
    FILE_READ_SUCCESS   = 3,
    FILE_READ_ERROR     = 4, 
    FILE_NAME_EMPTY     = 5
};

struct TNode* CreateNode(int code, float price, const char *pszName) 
{
    struct TNode *ptr = (struct TNode*)malloc(sizeof(struct TNode));
    ptr->code  = code;
    ptr->price = price;
    ptr->next  = NULL;

    if (pszName != NULL) {
        unsigned int nSize = strlen(pszName);
        ptr->name = (char*)malloc(sizeof(char) * nSize);
        strncpy(ptr->name, pszName, nSize);
    } else {
        ptr->name = (char*)malloc(sizeof(char) * SIZE_E);
        strncpy(ptr->name, "EMPTY", SIZE_E);
    }

    return ptr;
}

void addNode(struct TNode *node)
{
    if (pList == NULL) {
        pList = node;
    } else {
        struct TNode *ptr = pList;
        do {
            if (ptr->next == NULL) {
                ptr->next = node;
                ptr = NULL;
            } else {
                ptr = ptr->next;
            }
        } while (ptr != NULL);
    }
}

void PrintList() 
{
    for (struct TNode *ptr = pList; ptr != NULL; ptr = ptr->next) {
        printf("Code: %d\n", ptr->code);
        printf("Name: %s\n", ptr->name);
        printf("Price: %.2f\n\n", ptr->price);
    }
    printf("******\n\n");
}

enum STORAGE_STATUS WriteToFile(const char *filename) 
{
    if (filename != NULL) {
        FILE *pf = fopen(filename, "w+");
        if (pf) {
            for (struct TNode *ptr = pList; ptr != NULL; ptr = ptr->next) {
                fprintf(pf, "code:\t%d\n", ptr->code);
                fprintf(pf, "Name:\t%s\n", ptr->name);
                fprintf(pf, "Price:\t%.2f\n\n", ptr->price);
            }
            fclose(pf);
            return FILE_WRITE_SUCCESS;
        } else {
            return FILE_WRITE_ERROR;
        }
    } else {
        return FILE_NAME_EMPTY;
    }
}

int main(int argc, char* argv[]) 
{ 
    addNode(CreateNode(10, 122.45, "Running Pro"));
    addNode(CreateNode(20, 125.88, "Tennis Adv Evolution"));
    addNode(CreateNode(30, 102.12, "Running Elemental"));
    addNode(CreateNode(40, 98.33, "Tennis Junior"));
    addNode(CreateNode(55, 88.45, "Tempo Evolution 1"));

    if (argc > 1) {
        unsigned long nSize = argc > 1 ? strlen(argv[1]) : 0;
        char *filename = (char*)malloc(sizeof(char) * nSize);
        strncpy(filename, argv[1], nSize);
        if (WriteToFile(filename) == FILE_READ_SUCCESS) {
            printf("The file: %s has been written successfuly.\n", filename);
        } else {
            printf("There were an error trying to write into the file: %s.\n", filename);
        }
    } else {
        PrintList();
    }
    
    return EXIT_SUCCESS;
}