/**

	This file has been generated by Pedro Ontiveros.
	Filename: ../../advanced/static_sample.c
	Author: Pedro Ontiveros.
	email: ontiveros.pedro@gmail.com
	twitter: pontiveros_ar
	Sat Sep  3 11:19:59 EDT 2022

    clang: 
    $ clang -g source.c -o {binaryFile} ==> Result binary file + dsymb

    debug: 
    $ lldb {binary file} (object file)
    $ breakpoint set -file {source filename} --line {line}
    $ br s -f {source filename} -l {line}
    $ b {source filename} -l {line}
    $ next or n

**/

#include <stdio.h>
#include <stdlib.h>

void fn1(int a, int b) 
{
    static int i = 0;
    printf("initial value of i = %d.\n", i);
    i = a + b;
    printf("final value of i = %d.\n", i);
}

int main(int argc, char *argv[]) 
{
    int a, b =0;
    a = 2;
    b = 3;
    printf("Call fn1 with a = %d, b = %d.\n", a, b);
    fn1(a, b);
    printf("===========\n");

    a = 8;
    b = 4;
    printf("Call fn1 with a = %d, b = %d.\n", a, b);
    fn1(a, b);
    printf("end of program.\n");

    return EXIT_SUCCESS;
}
