/**

	This file has been generated by Pedro Ontiveros.
	Filename: ../../advanced/struct_sample.c
	Author: Pedro Ontiveros.
	email: ontiveros.pedro@gmail.com
	twitter: pontiveros_ar
	Sat Sep  3 11:43:53 EDT 2022

    clang: 
    $ clang -g source.c -o {binaryFile} ==> Result binary file + dsymb

    debug: 
    $ lldb {binary file} (object file)
    $ breakpoint set -file {source filename} --line {line}
    $ br s -f {source filename} -l {line}
    $ b {source filename} -l {line}
    $ next or n

**/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define EMPTY "EMPTY"
#define SIZE_E 5

struct TProduct {
    int code;
    float price;
    char* name;
};

struct TProduct* CreateTProduct(int code, float price, const char *pszName) {
    struct TProduct *ptr = (struct TProduct*)malloc(sizeof(struct TProduct));
    ptr->code  = code;
    ptr->price = price;

    if (pszName != NULL) {
        unsigned int nSize = strlen(pszName);
        ptr->name = (char*)malloc(sizeof(char) * nSize);
        strncpy(ptr->name, pszName, nSize);
    } else {
        ptr->name = (char*)malloc(sizeof(char) * SIZE_E);
        strncpy(ptr->name, "EMPTY", SIZE_E);
    }

    return ptr;
}

void DeleteTProduct(struct TProduct * product) 
{
    if (product != NULL) {
        if (product->name != NULL) {
            free(product->name);
            product->name = NULL;
        }

        free(product);
        product = NULL;
    }
}

void PrintProduct(struct TProduct* product) 
{
    if (product != NULL) {
        printf("Code: %d\n", product->code);
        printf("Name: %s\n", product->name);
        printf("Price: %f\n", product->price);
    } else {
        printf("Product is empty.\n");
    }
}

int main (int argc, char* argv[]) 
{
    struct TProduct* product = CreateTProduct(100, 12.34, "Tornillo para madera");
    PrintProduct(product);
    DeleteTProduct(product);
    PrintProduct(product);
    printf("*** end of program ***\n");
    return EXIT_SUCCESS;
}