/**

	This file has been generated by Pedro Ontiveros.
	Filename: ../../advanced/struct_sample.c
	Author: Pedro Ontiveros.
	email: ontiveros.pedro@gmail.com
	twitter: pontiveros_ar
	Sat Sep  3 11:43:53 EDT 2022

    clang: 
    $ clang -g source.c -o {binaryFile} ==> Result binary file + dsymb

    debug: 
    $ lldb {binary file} (object file)
    $ breakpoint set -file {source filename} --line {line}
    $ br s -f {source filename} -l {line}
    $ b {source filename} -l {line}
    $ next or n

**/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "tnode.h"

struct TNode *pStack = NULL;

void PrintNode(struct TNode* product);

void push(struct TNode *node) 
{
    if (pStack == NULL) {
        pStack = node;
    } else {
        node->next = pStack;
        pStack = node;
    }
}

void pop() 
{
    if (pStack != NULL) {
        if (pStack->next == NULL) {
            free(pStack);
            pStack = NULL;
        } else {
            struct TNode *node = pStack;

            pStack = node->next;

            free(node);
            node = NULL;
        }
    }
}

struct TNode* CreateNode(int code, float price, const char *pszName) {
    struct TNode *ptr = (struct TNode*)malloc(sizeof(struct TNode));
    ptr->code  = code;
    ptr->price = price;
    ptr->next  = NULL;

    if (pszName != NULL) {
        unsigned int nSize = strlen(pszName);
        ptr->name = (char*)malloc(sizeof(char) * nSize);
        strncpy(ptr->name, pszName, nSize);
    } else {
        ptr->name = (char*)malloc(sizeof(char) * SIZE_E);
        strncpy(ptr->name, "EMPTY", SIZE_E);
    }

    return ptr;
}

void PrintStack() 
{
    for (struct TNode *ptr = pStack; ptr != NULL; ptr = ptr->next) {
        PrintNode(ptr);
    }
}

void PrintNode(struct TNode* product) 
{
    if (product != NULL) {
        printf("Code: %d\n", product->code);
        printf("Name: %s\n", product->name);
        printf("Price: %.2f\n", product->price);
    } else {
        printf("Product is empty.\n");
    }

    printf("\n");
}

int main (int argc, char* argv[]) 
{
    push(CreateNode(1000, 1.25, "Construction Screw for wood"));
    push(CreateNode(1001, 3.22, "Exterior Screw for metal"));
    push(CreateNode(1002, 12.09, "Drywall scree"));
    push(CreateNode(1003, 6.27, "Arandela de presion"));
    push(CreateNode(1004, 4.35, "Arandela plana de plastico"));

    PrintStack();

    pop();pop();pop();
    printf("Remove 3 items.\n");
    PrintStack();
    printf("*** end of program ***\n");
    
    return EXIT_SUCCESS;
}