/**

	This file has been generated by Pedro Ontiveros.
	Filename: ../../advanced/tnode.h
	Author: Pedro Ontiveros.
	email: ontiveros.pedro@gmail.com
	twitter: pontiveros_ar
	Sun Sep  4 19:38:25 EDT 2022

    clang: 
    $ clang -g source.c -o {binaryFile} ==> Result binary file + dsymb

    debug: 
    $ lldb {binary file} (object file)
    $ breakpoint set -file {source filename} --line {line}
    $ br s -f {source filename} -l {line}
    $ b {source filename} -l {line}
    $ next or n

**/

#define EMPTY "EMPTY"
#define SIZE_E 5

struct TNode {
    int code;
    float price;
    char* name;
    struct TNode *next;
};
