
/**

	This file has been generated by Pedro Ontiveros.
	Filename: filew.c
	Author: Pedro Ontiveros.
	email: ontiveros.pedro@gmail.com
	twitter: pontiveros_ar
	Thu Jan 28 01:16:11 2016

**/


#include <stdio.h>
#include <stdlib.h>


int main(int argc, char *argv[]) {
	FILE *ptr = fopen("pedro.txt", "w+");

	if (ptr) {
		int lines = 0;
		for (lines = 0; lines < 1000; lines++) {
			fprintf(ptr, "Message from Pedro Ontiveros, line number: %d.\n", (lines + 1));
		}
		
	}
	fclose(ptr);

	exit(EXIT_SUCCESS);
}