
/**

	This file has been generated by Pedro Ontiveros.
	Filename: client.c
	Author: Pedro Ontiveros.
	email: ontiveros.pedro@gmail.com
	twitter: pontiveros_ar
	Tue Feb  9 00:49:10 2016

**/


#include <stdio.h>
#include <stdlib.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <string.h>


#define MAX_STRING 256

int main(int argc, char *argv[]) {
	int _socket;
	struct sockaddr_in _client; /* Estructura de socket proceso cliente */
	socklen_t size_addr;
	char buffer[MAX_STRING];

	if (argc != 2) {
		perror("ERROR: arguments wrong.");
		exit(EXIT_FAILURE);
	}

	/* Create socket */
	if ((_socket = socket(PF_INET, SOCK_STREAM, 0)) < 0) {
		perror("ERROR: creating the socket.");
		exit(EXIT_FAILURE);
	}

	memset(&_client, 0, sizeof(_client));
	_client.sin_family = AF_INET;
	_client.sin_port   = htons(9000); /* setear el orden de bytes de la red */

	if (!(inet_aton(argv[1], &_client.sin_addr))) {
		perror("ERROR: trying to set the address.");
		exit(EXIT_FAILURE);
	}

	size_addr = sizeof(_client);
	if (connect(_socket, (struct sockaddr *)&_client, size_addr)) {	
		perror("ERROR: connecting to remote server.");
		exit(EXIT_FAILURE);
	}

	memset(buffer, 0, sizeof(char) * MAX_STRING);
	puts("Connected to TCP/IP socket.");
	printf("Port: %d\n", ntohs(_client.sin_port));
	printf("Address: %s\n", inet_ntoa(_client.sin_addr));

	do {
		printf("Write your message: ");
		gets(buffer);

		if (strlen(buffer) > 0) {
			write(_socket, buffer, strlen(buffer));
		}
	} while (1);
		
	exit(EXIT_SUCCESS);
}
