
/**

	This file has been generated by Pedro Ontiveros.
	Filename: server.c
	Author: Pedro Ontiveros.
	email: ontiveros.pedro@gmail.com
	twitter: pontiveros_ar
	Thu Feb  4 02:45:48 2016

**/


#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <sys/types.h>
#include <netinet/in.h>
#include <unistd.h>


int main(int argc, char *argv[]) {
	int 	sockfd, newsockfd, port;
	struct sockaddr_in server_addr, client_addr;
	socklen_t client_len;
	char buffer[256];
	int n; // read chars from remote connection.

	if (argc < 2) {
		perror("ERROR: port has not been provided.");
		exit(EXIT_FAILURE);
	}

	sockfd = socket(AF_INET, SOCK_STREAM, 0); // create socket.
	if (sockfd < 0) {
		perror("ERROR: opening socket.");
		exit(EXIT_FAILURE);
	}

	port = atoi(argv[1]);
	server_addr.sin_family 		= AF_INET;    // Network family 
	server_addr.sin_addr.s_addr = INADDR_ANY; // Any address can connect ?
	server_addr.sin_port 		= htons(port);

	if (bind(sockfd, (struct sockaddr*)&server_addr, sizeof(server_addr)) < 0) {
		perror("ERROR: binding server.");
		exit(EXIT_FAILURE);
	}
	
	listen(sockfd, 5); // 5 means connections at the same time.

	client_len = sizeof(client_addr);
	newsockfd  = accept(sockfd, (struct sockaddr *)&client_addr, &client_len);
	if (newsockfd < 0) {
		perror("ERROR: accepting connection.");
		exit(EXIT_FAILURE);	
	}

	bzero(buffer, 256);
	n = read(newsockfd, buffer, 256);
	if (n < 0) {
		perror("ERROR: reading socket.");
	} else {
		printf("Remote Message: %s\n", buffer);
	}

	close(sockfd);
	close(newsockfd);

	exit(EXIT_SUCCESS);
}