/*
	This file has been generated by Pedro Ontiveros.
	Filename: ../../fundamentals/utils.c
	Author: Pedro Ontiveros.
	email: ontiveros.pedro@gmail.com
	twitter: pontiveros_ar
	Fri Mar  5 23:00:20 EST 2021
*/

#include "utils.h"
#include <stdio.h>
#include <stdlib.h>

void cleanScreen() {
    int i = 0;
    for (i = 0; i < 36; i++) {
        printf("\n");
    }
    fflush(stdout);
}

int selectMenu(const char *items[], int len) {
    int n, option = 0;
    
    for (n = 0; n < len; n++) {
        printf("%s\n", items[n]);
    }

    printf("Option: ");
    scanf("%d", &option);
    return option;
}

void quicksort(int *number,int first,int last) {
   int i, j, pivot, temp;

   if (first < last) {
      pivot=first;
      i=first;
      j=last;

      while(i<j) {
         while(number[i]<=number[pivot]&&i<last)
            i++;
         while(number[j]>number[pivot])
            j--;
         if(i<j){
            temp=number[i];
            number[i]=number[j];
            number[j]=temp;
         }
      }

      temp=number[pivot];
      number[pivot]=number[j];
      number[j]=temp;
      quicksort(number,first,j-1);
      quicksort(number,j+1,last);
   }
}

/************************/
/*** Sort By Exchange ***/
/************************/
void exchangeValues(int *a, int *b) {
    int aux = *a;
    *a = *b;
    *b = aux;
}

void sortByExchange(int items[], int len) {
    int i, j = 0;
    for (i = 0; i < (len -1); i++) {
        for (j = i + 1; j < len; j++) {
            if (items[i] > items[j]) {
                exchangeValues(&items[i], &items[j]);
            }
        }
    }
}

void printArrayInteger(int items[], int len) {
    int i = 0; 
    for (i = 0; i < len; i++) {
        printf("order %03\t value: %d\n", i, items[i]);
    }
}