
/**

	This file has been generated by Pedro Ontiveros.
	Filename: liberr.h
	Author: Pedro Ontiveros.
	email: ontiveros.pedro@gmail.com
	twitter: pontiveros_ar
	Sun Jan 24 16:13:52 2016

**/

#ifndef __FILENAME__
#define __FILENAME__
#endif // __FILENAME__