
/**

	This file has been generated by Pedro Ontiveros.
	Filename: main.c
	Author: Pedro Ontiveros.
	email: ontiveros.pedro@gmail.com
	twitter: pontiveros_ar
	Sun Jan 24 16:38:43 2016

**/


#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "sample1.h"

void messgaeSample() {
	char msg[256];
	printf("Insert your message: ");
	/* fgets(msg, sizeof(char) * 256, stdin); // read a line from stdin */
	scanf("%s", msg);
	printMessage(msg);
}

void sumSample() {
	printf("Sum Sample Result: %.2f\n", sumDouble(10.5f , 25.0f));
}

int main(int argc, char *argv[]) {	
	int option;

	do {
		printf("Option (0 for exit): ");
		option = getchar();
		fflush(stdin);

		switch (option) {
			case '1': {
				messgaeSample();
			} break;
			case '2': {
				sumSample();
			}
		}	
	} while (option > '0');

	exit(EXIT_SUCCESS);
}
