
/**

	This file has been generated by Pedro Ontiveros.
	Filename: liberr.h
	Author: Pedro Ontiveros.
	email: ontiveros.pedro@gmail.com
	twitter: pontiveros_ar
	Sun Jan 24 16:13:52 2016.
**/

#ifndef __SAMPLE1_H_20160124__
#define __SAMPLE1_H_20160124__
#include <stdarg.h> 

void printMessage(char *message);
double sumDouble(double a, double b);

#endif // __SAMPLE1_H_20160124__