
/**

	This file has been generated by Pedro Ontiveros.
	Filename: child.c
	Author: Pedro Ontiveros.
	email: ontiveros.pedro@gmail.com
	twitter: pontiveros_ar
	Mon Jan 18 22:04:40 2016

**/


#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>


void fakeworker() {
	int n = 0;
	for (n = 0; n < 5; n++) {
		printf("working line number %d\n", (n + 1));
		sleep(1);
	}
}

int main(int argc, char *argv[]) {
	
	pid_t child;

	if ((child = fork()) == -1) {
		perror("fork ERROR");
		exit(EXIT_FAILURE);

	} else if (child == 0) {
		puts("\nChild process");
		printf("PID: %d\n", getpid());
		printf("PPID: %d\n", getppid()); 
		/* if the parent process id is equal 1, means that parent process already finished when child asked for getppid() */
		exit(EXIT_SUCCESS);

	} else {
		puts("Parent process");
		printf("PID: %d\n", getpid());
		printf("PPID: %d\n", getppid());
		fakeworker(); /* only for delay the parent process */
	}

	exit(EXIT_SUCCESS);
}