/**

	This file has been generated by Pedro Ontiveros.
	Filename: ../../fundamentals/arrays.c
	Author: Pedro Ontiveros.
	email: ontiveros.pedro@gmail.com
	twitter: pontiveros_ar
	Wed Mar  3 00:26:25 EST 2021

    clang: 
    $ clang -g source.c -o {binaryFile} ==> Result binary file + dsymb

    debug: 
    $ lldb {binary file} (object file)
    $ breakpoint set -file {source filename} --line {line}
    $ br s -f {source filename} -l {line}
    $ b {source filename} -l {line}
    $ next or n

**/

#include <stdio.h>
#include <stdlib.h>

#define MAX_STRING 100

char* generateStrings() {
    --generate here ramdom string
}

int main(int argc, char* argv[]) {


    for () {

    }


    printf("End of program\n");
    exit(EXIT_SUCCESS);    
}