
/**

	This file has been generated by Pedro Ontiveros.
	Filename: ../../fundamentals/main.h
	Author: Pedro Ontiveros.
	email: ontiveros.pedro@gmail.com
	twitter: pontiveros_ar
	Tue Mar  2 22:40:59 EST 2021

    clang: 
    $ clang -g source.c -o {binaryFile} ==> Result binary file + dsymb

    debug: 
    $ lldb {binary file} (object file)
    $ breakpoint set -file {source filename} --line {line}
    $ br s -f {source filename} -l {line}
    $ b {source filename} -l {line}
    $ next or n
**/

#include <stdio.h>
#include <stdlib.h>

int main () {
    /* ANSI C Std data types */

    char    c = 'c';
    short   s = 1;
    int     i = 1000;
    long    l = 10000000;
    float   f = 1092.92;
    double  d = 91928.99882;

    printf("char size : \t%ld bytes - char value %c\n", sizeof(c), c);
    printf("short size : \t%ld bytes - char value %d\n", sizeof(s), s);
    printf("int size : \t%ld bytes - char value %d\n", sizeof(i), i);
    printf("long size : \t%ld bytes - char value %ld\n", sizeof(l), l);
    printf("float size : \t%ld bytes - char value %f\n", sizeof(f), f);
    printf("double size : \t%ld bytes - char value %lf\n", sizeof(f), f);

    printf("End of program\n");
    exit(EXIT_SUCCESS);
}