
/**

	This file has been generated by Pedro Ontiveros.
	Filename: ../../fundamentals/operators.c
	Author: Pedro Ontiveros.
	email: ontiveros.pedro@gmail.com
	twitter: pontiveros_ar
	Tue Mar  2 23:15:08 EST 2021

    clang: 
    $ clang -g source.c -o {binaryFile} ==> Result binary file + dsymb

    debug: 
    $ lldb {binary file} (object file)
    $ breakpoint set -file {source filename} --line {line}
    $ br s -f {source filename} -l {line}
    $ b {source filename} -l {line}
    $ next or n

**/

#include <stdio.h>
#include <stdlib.h>

int mainMenu() {
    int option = 0;
    
    printf("Basic Arithmetic Operations: \n");
    printf("1- add\n");
    printf("2- sub\n");
    printf("3- mul\n");
    printf("4- div\n\n");
    printf("0- Exit\n\n");
    printf("Option: ");
    scanf("%d", &option);
    return option;
}

int insertNumber(char c) {
    int value = 0;
    printf("Insert integer value %c: ", c);
    scanf("%d", &value);
    return value;
}

int add(int a , int b)   { return (a + b); }
int sub(int a , int b)   { return (a - b); }
int mult(int a , int b)  { return (a * b); }
int divi(int a , int b)  { return (a / b); }

int performOperation(int option) {
    int a, b, c, result = 0;

    a = insertNumber('A');
    b = insertNumber('B');

    switch (option) {
        case 1: result = add(a, b);  break;
        case 2: result = sub(a, b);  break;
        case 3: result = mult(a, b); break;
        case 4: result = divi(a, b); break;
    }

    printf("Result: %d\n", result);
    printf("continue...?(0=NO 1=YES): ");
    scanf("%d",&c);
    return c;
}

void cleanScreen() {
    int i = 0;
    for (i = 0; i < 100; i++) {
        printf("\n");
    }
    fflush(stdout);
}

int main () {
    /* Basic Arithmetic Operators */
    int option = 0;

    do {
        cleanScreen();
        option = mainMenu();
        if (option > 0) {
            option = performOperation(option);
        }
    } while (option != 0);
    
    printf("End of program\n");
    exit(EXIT_SUCCESS);
}