/*
	This file has been generated by Pedro Ontiveros.
	Filename: ../../fundamentals/utils.c
	Author: Pedro Ontiveros.
	email: ontiveros.pedro@gmail.com
	twitter: pontiveros_ar
	Fri Mar  5 23:00:20 EST 2021
*/

#include "utils.h"
#include <stdio.h>
#include <stdlib.h>

void cleanScreen() {
    int i = 0;
    for (i = 0; i < 36; i++) {
        printf("\n");
    }
    fflush(stdout);
}

int selectMenu(const char *items[], int len) {
    int n, option = 0;
    
    for (n = 0; n < len; n++) {
        printf("%s\n", items[n]);
    }

    printf("Option: ");
    scanf("%d", &option);
    return option;
}
