/*
	This file has been generated by Pedro Ontiveros.
	Filename: ../../fundamentals/utils.h
	Author: Pedro Ontiveros.
	email: ontiveros.pedro@gmail.com
	twitter: pontiveros_ar
	Fri Mar  5 22:59:32 EST 2021
*/

#ifndef __UTILS_H_20210305__
#define __UTILS_H_20210305__

void cleanScreen();
int selectMenu(const char *items[], int len);
void quicksort(int number[25],int first,int last);
void sortByExchange(int items[], int len);
void printArrayInteger(int items[], int len);

#endif // __UTILS_H_20210305__